### ISSUE TITLE
AMD Ryzen and C6 states

### ISSUE THREAD

**Issue by thorsteneb** [freenas/documentation#199]
Putting this here to track hardware install docs and Ryzen / C6. In FreeNAS 11.3, turning off C6 state / "Cool'N'Quiet" is just about a requirement to have a stable Ryzen system. I say "just about" because it has helped multiple Ryzen owners; at the same time, it is possible that some boards work just fine with it on.

I think it's worth tracking this down with Ryzen owners on the forum, or Ryzen test beds that ixSystems may have, and see whether this is also required for TrueNAS 12.0. If so, it can arguably be part of the "install on hardware" instructions, to make sure people have a great experience out of the box and don't have a first impression of "TrueNAS is unstable", if they are installing on Ryzen.

**Comment by q5sys** [comment]
Thanks for the info, do you have any links where people are discussing this, so I can give the QE Team something to work with?

**Comment by thorsteneb** [comment]
Here are some links.

jira: https://jira.ixsystems.com/browse/NAS-104597
Forum, Cool'n'Quiet: https://www.ixsystems.com/community/threads/frustrated-with-amd-ryzen-stability-on-11-2-u5.78263/#post-544741
Forum, C6: https://www.ixsystems.com/community/threads/freenas-hardware-is-shutting-down.82532/#post-578125

**Comment by q5sys** [comment]
Thanks for the info, if you come upon more issues like this, be sure to let us knwo.
https://github.com/freenas/documentation/pull/222
