### ISSUE TITLE
API problem

### ISSUE THREAD

**Issue by Lukerd-29-00** [freenas/documentation#254]
When I use the code from https://www.ixsystems.com/documentation/freenas/11.3-U3.2/api.html to try to create a pool, the requests() function will return a 409 response and throw a value error. I am running version 11.3-U4 on a gns3 virtual network. the _get_disks() function returns the disks on the machine as expected, so it is not a connectivity issue. The .py file is attached. 
[freeNAS.zip](https://github.com/freenas/documentation/files/5007277/freeNAS.zip)

**Comment by q5sys** [comment]
Thanks for the ticket.
If you're sure that the values are sending in the call are correct, and think there's a bug in the API middleware, file a ticket here: https://jira.ixsystems.com/projects/NAS/issues/ as that'll be an engineering issue.  The API docs are auto generated based on the source and we do automated API testing, so if there's any issue the Engineering Team will be able to track it down. 

We also have a community slack instance for people chatting and working together on stuff.  If you want to join there and talk to others about API scripting you can join here: truenas.slack.com
