### ISSUE TITLE
Google Analytics are missing / Feedback does not work

### ISSUE THREAD

**Issue by aidik** [freenas/documentation#257]
While I can see that the GA are enabled and set to correct value in [`config.toml`](https://github.com/freenas/documentation/blob/master/config.toml#L52) the script is not present in the output on https://docs.ixsystems.com/ and https://www.truenas.com/docs/ respectively. 

This leads to a lost visitor count and also renders the feedback feature ineffective. 

From GA I can see that this issue manifested around July 22nd.

_As an underline comment, please consider the use of Google Tag Manager over plain Google Analytics._

**Comment by Mrt134** [comment]
We've resolved the analytics bug and implemented Tag Manager for the site (https://github.com/freenas/documentation/pull/265). That should take care of the issue!
