### ISSUE TITLE
TrueNAS Core 12: Cloud Sync post-script

### ISSUE THREAD

**Issue by mhaluska** [freenas/documentation#259]
I'm missing some details for post-script. Is for example possible pass return code (or another vars) from task to this post-script?
Source: https://www.truenas.com/docs/hub/tasks/scheduled/cloudsync/

**Comment by Mrt134** [comment]
Thanks for opening an issue! We'll look into expanding this text as soon as we can.

**Comment by Mrt134** [comment]
I'm working on text changes for the article now, but the short answer is that you can pass many different environment variables to either pre or post script fields. There are general variables and variables that are specific to the Cloud Storage Provider being used. Post-script is not allowed to run if the task is not successful. Here's an early list of task variables:
CLOUD_SYNC_ID
CLOUD_SYNC_DESCRIPTION
CLOUD_SYNC_DIRECTION
CLOUD_SYNC_TRANSFER_MODE
CLOUD_SYNC_ENCRYPTION
CLOUD_SYNC_FILENAME_ENCRYPTION
CLOUD_SYNC_ENCRYPTION_PASSWORD
CLOUD_SYNC_ENCRYPTION_SALT
CLOUD_SYNC_SNAPSHOT
There also are provider-specific variables like CLOUD_SYNC_CLIENT_ID or CLOUD_SYNC_TOKEN or CLOUD_SYNC_CHUNK_SIZE
Remote storage settings:
CLOUD_SYNC_BUCKET
CLOUD_SYNC_FOLDER
Local storage settings:
CLOUD_SYNC_PATH
