### ISSUE TITLE
Sharing encrypted data

### ISSUE THREAD

**Issue by distancesprinter** [freenas/documentation#287]
Documentation does not cover sending or receiving from unencrypted/encrypted source to encrypted destination.  Documentation does not have a legend describing the encryption icons that appear under Storage > Pools.

**Comment by Mrt134** [comment]
Thanks for opening this issue, we'll look into updates for the docs!

**Comment by Mrt134** [comment]
Just noticed we've got a duplicate, so I'm going to close this one as the other has the comments.

**Comment by Mrt134** [comment]
ha, scratch that, just the same title - it's definitely Friday :)

**Comment by Mrt134** [comment]
Encryption docs have been updated with iconography in https://github.com/freenas/documentation/pull/336. There's some further work being done to improve documentation about send/receive to an encrypted destination, so keep an eye on the site in the near future for those docs. Thanks!
