### ISSUE TITLE
Consolidated Release of Documentation

### ISSUE THREAD

**Issue by Fraser-T** [freenas/documentation#308]
Hi,
would it be possible for a consolidated release either on this repo or on the documentation site, that consists of a collection of all the documentation in PDFs for easy access when offline?

**Comment by Mrt134** [comment]
Thanks for opening this issue! I'll have to do some research into Hugo > PDF conversions, but that could be possible.

**Comment by Mrt134** [comment]
It's been requested that we consolidate Community issue reporting into the NAS Jira project at https://jira.ixsystems.com/projects/NAS/ . I've got this request added to our tracker, so it's not being closed outright, just moved. :)
