### ISSUE TITLE
Best practices in TLS setup

### ISSUE THREAD

**Issue by CyrilleVladimirov** [freenas/documentation#310]
Hi!

I think it is better to avoid TLS 1.0 and 1.1 from default setup of TLS  ciphers and by default marked only 1.2 and 1.3.
Regards

**Comment by Mrt134** [comment]
Yes, you're absolutely right. I've got a simple update to https://www.truenas.com/docs/hub/initial-setup/best-practices/manage-tls/ to explain this. Thanks for noticing and saying something!
